export default {
  bg: [
    {name: '1', url: '/img/pr2/bg1.png'},
    {name: '2', url: '/img/pr2/bg2.png'},
  ],
  furniture: [
    {
      burl: '/img/moon/1.png',
      url: '/img/moon/b1.png',
      w: 350,
      h: 367,
      s: 'width:30vw;height:calc(30vw * ' + 367 / 350 + ')',
      top: '2vh',
      left: '4vw',
    },
    {
      burl: '/img/moon/2.png',
      url: '/img/moon/b2.png',
      w: 718,
      h: 383,
      s: 'width:60vw;height:calc(60vw * ' + 383 / 718 + ')',
      top: '6vh',
      left: '4vw',
    },
    {
      burl: '/img/moon/3.png',
      url: '/img/moon/b3.png',
      w: 718,
      h: 374,
      s: 'width:70vw;height:calc(70vw * ' + 374 / 718 + ')',
      top: '2vh',
      left: '4vw',
    },
  ],
  person: [
    //成人
    {
      name: 'girl',
      hair: 1,
      coat: 1,
      face: 3,
      leg: 1,
      w: 124,
      h: 232,
      offset: 3,
      faces: [
        {
          name: '',
          url: '/img/girl/faces/1.png',
          w: 230,
          h: 332,
          t: 2,
          l: 36,
        },
        {
          name: '',
          url: '/img/girl/faces/2.png',
          w: 230,
          h: 332,
          t: 2,
          l: 36,
        },
        {
          name: '',
          url: '/img/girl/faces/3.png',
          w: 230,
          h: 332,
          t: 2,
          l: 36,
        },
        {
          name: '',
          url: '/img/girl/faces/4.png',
          w: 230,
          h: 332,
          t: 2,
          l: 36,
        },
      ],
      hairs: [
        {
          name: '',
          url: '/img/girl/hair1.png',
          w: 283,
          h: 353,
          t: -12,
          l: 29,
        },
        {
          name: '',
          url: '/img/girl/hair2.png',
          w: 283,
          h: 353,
          t: -13,
          l: 29,
        },
        {
          name: '',
          url: '/img/girl/hair3.png',
          w: 283,
          h: 353,
          t: -12,
          l: 29,
        },
        {
          name: '',
          url: '/img/girl/hair4.png',
          w: 283,
          h: 353,
          t: -12,
          l: 29,
        },
      ],
      coats: [
        {
          name: '',
          url: '/img/girl/coats/1.png',
          w: 290,
          h: 310,
          t: 40,
          l: 29,
        },
        {
          name: '',
          url: '/img/girl/coats/2.png',
          w: 631,
          h: 451,
          t: 6,
          l: -14,
        },
        {
          name: '',
          url: '/img/girl/coats/3.png',
          w: 407,
          h: 351,
          t: 53,
          l: 19,
        },
        {
          name: '',
          url: '/img/girl/coats/4.png',
          w: 389,
          h: 366,
          t: 33,
          l: 11,
        },
      ],
      legs: [
        {
          name: '',
          url: '/img/girl/legs/1.png',
          w: 562,
          h: 318,
          t: 109,
          l: 11 - 22,
        },
        {
          name: '',
          url: '/img/girl/legs/2.png',
          w: 219,
          h: 487,
          t: 97 + 16,
          l: 39,
        },
        {
          name: '',
          url: '/img/girl/legs/3.png',
          w: 278,
          h: 472,
          t: 112,
          l: -15 + 39,
        },
        {
          name: '',
          url: '/img/girl/legs/4.png',
          w: 285,
          h: 475,
          t: 114,
          l: -15 + 63,
        },
      ],
    },
    {
      name: 'boy',
      hair: 0,
      coat: 0,
      face: 3,
      leg: 1,
      w: 124,
      h: 230,
      offset: 16,
      faces: [
        {
          name: '',
          url: '/img/boy/faces/1.png',
          w: 234,
          h: 280,
          t: -7,
          l: 33,
        },
        {
          name: '',
          url: '/img/boy/faces/2.png',
          w: 234,
          h: 280,
          t: -7,
          l: 33,
        },
        {
          name: '',
          url: '/img/boy/faces/3.png',
          w: 234,
          h: 280,
          t: -7,
          l: 33,
        },
        {
          name: '',
          url: '/img/boy/faces/4.png',
          w: 234,
          h: 280,
          t: -7,
          l: 33,
        },
      ],
      hairs: [
        {
          name: '',
          url: '/img/boy/hair1.png',
          w: 233,
          h: 154,
          t: -11,
          l: 34,
        },
        {
          name: '',
          url: '/img/boy/hair2.png',
          w: 231,
          h: 156,
          t: -11,
          l: 34,
        },
        {
          name: '',
          url: '/img/boy/hair3.png',
          w: 245,
          h: 188,
          t: -15,
          l: 31,
        },
        {
          name: '',
          url: '/img/boy/hair4.png',
          w: 226,
          h: 158,
          t: -10,
          l: 33,
        },
      ],
      coats: [
        {
          name: '',
          url: '/img/boy/coats/1.png',
          w: 485,
          h: 330,
          t: 40,
          l: 13,
        },
        {
          name: '',
          url: '/img/boy/coats/2.png',
          w: 410,
          h: 567,
          t: -16,
          l: 10,
        },
        {
          name: '',
          url: '/img/boy/coats/3.png',
          w: 340,
          h: 352,
          t: 50,
          l: 20,
        },
        {
          name: '',
          url: '/img/boy/coats/4.png',
          w: 504,
          h: 411,
          t: 18,
          l: -27,
        },
      ],
      legs: [
        {
          name: '',
          url: '/img/boy/legs/1.png',
          w: 219,
          h: 405,
          t: 117,
          l: 33,
        },
        {
          name: '',
          url: '/img/boy/legs/2.png',
          w: 598,
          h: 276,
          t: 118,
          l: -13,
        },
        {
          name: '',
          url: '/img/boy/legs/3.png',
          w: 288,
          h: 394,
          t: 117,
          l: 15,
        },
        {
          name: '',
          url: '/img/boy/legs/4.png',
          w: 584,
          h: 318,
          t: 118,
          l: -29,
        },
      ],
    },
  ],
  others: [
    {name: '', url: '/img/others/dangao.png', w: 921 / 3, h: 739 / 3},
    {name: '', url: '/img/others/hua.png', w: 639 / 3, h: 1014 / 3},
    {name: '', url: '/img/others/huli.png', w: 815 / 3, h: 831 / 3},
    {name: '', url: '/img/others/jiubei.png', w: 771 / 3, h: 744 / 3},
    {name: '', url: '/img/others/kafei.png', w: 589 / 3, h: 617 / 3},
    {
      name: '',
      url: '/img/others/kafeizuoyi.png',
      w: 986 / 3,
      h: 1242 / 3,
    },
    {name: '', url: '/img/others/liwu.png', w: 718 / 3, h: 792 / 3},
    {name: '', url: '/img/others/qiqiu.png', w: 778 / 3, h: 1019 / 3},
  ],
}
